ALTER TABLE Pharmacies
  ADD CONSTRAINT PK_Pharm_ID PRIMARY KEY (Pharm_ID),
  ADD CONSTRAINT Pharm_house_limit CHECK (House BETWEEN 1 AND 200);

ALTER TABLE Employees
  ADD CONSTRAINT PK_Empl_ID PRIMARY KEY (Empl_ID),
  ADD CONSTRAINT FK_Pharm_ID FOREIGN KEY (Pharm_ID) REFERENCES Pharmacies(Pharm_ID) ON DELETE CASCADE,
  ADD CONSTRAINT Salary_limit CHECK (Salary > 0);

ALTER TABLE Medicines
  ADD CONSTRAINT PK_Med_ID PRIMARY KEY (Med_ID),
  ADD CONSTRAINT Price_limit CHECK (Price > 0);

ALTER TABLE Availability
  ADD CONSTRAINT FK_Med_ID FOREIGN KEY (Med_ID) REFERENCES Medicines(Med_ID) ON DELETE CASCADE,
  ADD CONSTRAINT FK_Pharm_ID FOREIGN KEY (Pharm_ID) REFERENCES Pharmacies(Pharm_ID) ON DELETE CASCADE,
  ADD CONSTRAINT Qnt_limit CHECK (Qnt >= 0);
